### ISSUE TITLE
Validation error in field "Continent"

### ISSUE THREAD

**Issue by jblumtritt** [cceh/IMDI-Environment-for-CMDI-Maker#12]
Value '' is not facet-valid with respect to enumeration '[Unknown, Unspecified, Africa, Asia, Europe, Australia, Oceania, North-America, Middle-America, South-America]'. It must be a value from the enumeration.

**Comment by jblumtritt** [comment]
also the value list in the Interface must be "Unknown, Unspecified, Africa, Asia, Europe, Australia, Oceania, North-America, Middle-America, South-America".
The current interface displays values from ELDP-Environment

**Comment by MigRam** [comment]
closed #13
