### ISSUE TITLE
The function "Create one session per file" should always take the file name as basis for the session name

### ISSUE THREAD

**Issue by jblumtritt** [cceh/IMDI-Environment-for-CMDI-Maker#4]
You can use the resources-tab to create new sessions based on selected files. This basically adds the file names to the resources-section of the new session.

Additionally, when choosing to "create one session per file" along with the option "EAF" the file name of the EAF-file (without file extension) is automatically filled in to the session-name-field of the profile. 
This makes it significantly easier to manage the collection especially when creating large numbers of sessions.

I expect the same behaviour when using the function "create one session per file" with the options "selected files", "WAV", "MP4" or "MPG". Instead those options result in the creation of "unnamed sessions". see screenshots below.

I suspect this is an IMDI-environment issue because the described expected behaviour is 'correctly' implemented in the ELDP-environment.

![cmdi-maker-session-per-file-1](https://cloud.githubusercontent.com/assets/3205396/11586333/9473b0c6-9a72-11e5-937f-e8ad0c20fbe0.jpg)
![cmdi-maker-session-per-file-2](https://cloud.githubusercontent.com/assets/3205396/11586335/9bda4d0c-9a72-11e5-82bd-c3bb3c5d67de.jpg)

**Comment by jblumtritt** [comment]
The issue was also raised by several CMDI Maker users and was discussed internally by the CMDI Maker Support group.
- https://redmine.uni-koeln.de/issues/2047

**Comment by polyrainbow** [comment]
This bug has passed unnoticed because of the wrong variable called "name". It wouldn't throw an exception because "name" is defined in the global namespace: http://stackoverflow.com/questions/26562719/is-variable-called-name-always-defined-in-javascript
