### ISSUE TITLE
a ref-attribute with reference to the resource ID is missing in <WrittenResource/> and <MediaFile/> elements in cmdi-output

### ISSUE THREAD

**Issue by jblumtritt** [cceh/IMDI-Environment-for-CMDI-Maker#6]
The XML-Output generated by the CMDI Maker when producing CMDI files from the imdi-session profile is missing the ref-attribute that refers to the respective <ResourceProxy> element in the header section

more like
`<WrittenResource ref="res_q942398232548023042390429034">`  
instead of just
`<WrittenResource>`

**Comment by MigRam** [comment]
closed #11
